#!/usr/bin/env bash
# Phase 1 baseline redactor for embercap charge-limit research.
# See charter §4.1–§4.5 at
#   docs/superpowers/specs/2026-04-24-embercap-charge-limit-research-charter-design.md
#
# Usage:
#   bash scripts/redact-baseline.sh \
#        <status_txt> <probe_txt> <diag_json> <pmset_txt> <ioreg_txt> \
#        <output_dir>
#
# Env overrides (for fixture testing):
#   REDACT_USER      — override the username treated as a secret
#   REDACT_HOSTNAME  — override the local hostname treated as a secret
set -euo pipefail

if [ "$#" -ne 6 ]; then
  echo "usage: $0 <status> <probe> <diag> <pmset> <ioreg> <output_dir>" >&2
  exit 2
fi

IN_STATUS="$1"
IN_PROBE="$2"
IN_DIAG="$3"
IN_PMSET="$4"
IN_IOREG="$5"
OUT_DIR="$6"

mkdir -p "$OUT_DIR"

LIVE_USER="${REDACT_USER:-${USER:-unknown}}"
if [ -n "${REDACT_HOSTNAME:-}" ]; then
  LIVE_HOST="$REDACT_HOSTNAME"
else
  LIVE_HOST="$(scutil --get LocalHostName 2>/dev/null || hostname -s 2>/dev/null || hostname 2>/dev/null || echo unknown)"
fi

# Kernel-line hostname token: match "Darwin <host> X.Y.Z" only. In
# `uname -a` output the hostname is always followed by a whitespace-
# separated version triplet, which distinguishes it from later literal
# tokens such as "Darwin Kernel Version …" that must be preserved per
# charter §4.2.
KERNEL_HOST_SED='s/(Darwin )([^[:space:]\\"]+)([[:space:]]+[0-9]+\.[0-9]+\.[0-9]+)/\1<HOSTNAME-REDACTED>\3/g'

# Field-scoped masker: matches  "Key" = "val"  (ioreg)  and  "Key" : "val"  (JSON).
field_scoped_sed() {
  local key="$1" placeholder="$2"
  printf 's/(\"%s\"[[:space:]]*=[[:space:]]*\")[^\"]*(\")/\\1%s\\2/g;' "$key" "$placeholder"
  printf 's/(\"%s\"[[:space:]]*:[[:space:]]*\")[^\"]*(\")/\\1%s\\2/g;' "$key" "$placeholder"
}

REDACT_SED=""
for k in BatterySerialNumber "Hardware Serial Number" "Serial Number" \
         IOPlatformSerialNumber PlatformSerialNumber MACAddress IOMACAddress \
         Serial; do
  REDACT_SED+="$(field_scoped_sed "$k" "<SERIAL-REDACTED>")"
done
REDACT_SED+="$(field_scoped_sed IOPlatformUUID "<UUID-REDACTED>")"
REDACT_SED+="$(field_scoped_sed UUID "<UUID-REDACTED>")"
REDACT_SED+="$(field_scoped_sed serial "<SERIAL-REDACTED>")"

# serial <value>  — human-readable status form. Accepts both colon
# (`serial: V`) and column-aligned (`serial    V`) separators.
STATUS_SERIAL_SED='s/(^[[:space:]]*serial[[:space:]:]+)[^[:space:]].*$/\1<SERIAL-REDACTED>/'

# Home path and username (both forms: in paths, and as standalone words).
USER_SED="s|/Users/${LIVE_USER}|/Users/<USER-REDACTED>|g;"
USER_SED+="s/[[:<:]]${LIVE_USER}[[:>:]]/<USER-REDACTED>/g;"

HOST_SED="s/[[:<:]]${LIVE_HOST}[[:>:]]/<HOSTNAME-REDACTED>/g;"

redact() {
  local src="$1" dst="$2"
  sed -E \
    -e "$REDACT_SED" \
    -e "$KERNEL_HOST_SED" \
    -e "$STATUS_SERIAL_SED" \
    -e "$USER_SED" \
    -e "$HOST_SED" \
    "$src" > "$dst"
}

redact "$IN_STATUS" "$OUT_DIR/embercap-status.txt"
redact "$IN_PROBE"  "$OUT_DIR/embercap-probe.txt"
redact "$IN_DIAG"   "$OUT_DIR/diag.json"
redact "$IN_PMSET"  "$OUT_DIR/pmset-batt.txt"
redact "$IN_IOREG"  "$OUT_DIR/ioreg-AppleSmartBattery.txt"

cat > "$OUT_DIR/README.md" <<EOF
# Baseline artifacts — 2026-04-24

Per charter §7.1 and plan Phase 1. Redacted outputs of read-only Phase 1
commands. Raw inputs remained under \`/tmp\` and were not committed
(charter R6). Redaction rules: charter §4.1–§4.3. Placeholders:
\`<SERIAL-REDACTED>\`, \`<UUID-REDACTED>\`, \`<HOSTNAME-REDACTED>\`,
\`<USER-REDACTED>\`, \`<MAC-REDACTED>\`.

Files:

- \`embercap-status.txt\` — redacted \`.build/debug/embercap status\`.
- \`embercap-probe.txt\`  — redacted \`.build/debug/embercap probe\`.
- \`diag.json\`           — redacted \`.build/debug/embercap diag --format=json\`.
- \`pmset-batt.txt\`      — redacted \`pmset -g batt\`.
- \`ioreg-AppleSmartBattery.txt\` — redacted \`ioreg -rn AppleSmartBattery\`.

Generated by \`scripts/redact-baseline.sh\`.
EOF

echo "ok: wrote 5 redacted files + README.md to $OUT_DIR"
